# Generated by Django 3.2.16 on 2024-12-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='numberWorkers',
            field=models.IntegerField(default=0, verbose_name='Количество работников'),
        ),
    ]
