# Generated by Django 3.2.16 on 2024-12-13 19:06

from django.db import migrations, models
import workshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='workingHours',
            field=models.CharField(max_length=11, validators=[workshop.models.validate_time_range], verbose_name='Рабочие часы'),
        ),
    ]
