# Generated by Django 3.2.16 on 2024-12-14 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_alter_worker_workinghours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='supervisor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshop_supervised', to='workshop.worker', verbose_name='Начальник цеха'),
        ),
    ]
