# Generated by Django 3.2.16 on 2024-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderNumber', models.IntegerField(unique=True, verbose_name='Номер заказа')),
                ('startDate', models.DateField(verbose_name='Дата начала')),
                ('endDate', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('admin', 'Администратор'), ('supervisor', 'Начальник цеха'), ('worker', 'Рабочий')], default='working', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
