# Generated by Django 3.2.16 on 2024-12-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workshop', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='workshops',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='workshop.workshop', verbose_name='Цех'),
        ),
    ]
