# Generated by Django 3.2.16 on 2024-12-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_ordernumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('in progress', 'в процессе'), ('completed', 'завершен'), ('cancelled', 'отменен')], default='working', max_length=20, verbose_name='Статус'),
        ),
    ]
